name: test_tom
description: TOM test
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  intl: ^0.17.0



dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
